# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # ------- BACK-OFFICE /admin -------
        admin:
            pattern: ^/admin
            provider: app_user_provider
            lazy: true

            form_login:
                login_path:  admin_login
                check_path:  admin_login
                default_target_path: app_admin_dashboard_index

                username_parameter: _username
                password_parameter: _password
                csrf_parameter:    _csrf_token
                enable_csrf: true

            logout:
                path:   admin_logout
                target: admin_login

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800
                path:     /

        # ------- SITE PUBLIC -------
        main:
            pattern: ^/
            provider: app_user_provider
            lazy: true

            form_login:
                login_path:  app_login
                check_path:  app_login
                default_target_path: home
                enable_csrf: true
                username_parameter: _username
                password_parameter: _password
                csrf_parameter: _csrf_token

            logout:
                path:   app_logout
                target: app_login

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 7200
                path:     /

    access_control:
        # back-office
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin,         roles: ROLE_ADMIN }

        # site public
        - { path: ^/login$,    roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
