# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email           # ← c’est bien le champ « email » de ton entité

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: app_user_provider
            lazy: true

            form_login:
                login_path:  app_login     # GET  /admin/login  → affiche le formulaire
                check_path:  app_login     # POST /admin/login  → traite la soumission
                default_target_path: admin # vers /admin après connexion

                # ★ on fait correspondre exactement les names du <form> ★
                username_parameter: _username
                password_parameter: _password
                csrf_parameter:    _csrf_token
                enable_csrf:       true

            logout:
                path:   app_logout
                target: app_login

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800  # 7 jours
                path:     /

        main:          # le reste du site n’est pas protégé
            pattern: ^/
            security: false

    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin,         roles: ROLE_ADMIN }
