services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/srv/app:cached
    working_dir: /srv/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE:       GoldenGoat
      MYSQL_USER:           user
      MYSQL_PASSWORD:       secret
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
